chore: always run lint (by always running warm-up cache) and always report linting errors

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,9 +43,6 @@ jobs:
   warm-up-cache:
     name: Warm up the cache
     runs-on: ubuntu-latest
-    needs:
-      - changes
-    if: ${{ needs.changes.outputs.code == 'true' }}
     steps:
       - name: Check out code
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
@@ -175,6 +172,7 @@ jobs:
 
       - name: Run lint
         shell: bash
+        id: tests
         run: |
           npm run lint -- --format=json --output-file reports/lint-report.json
         continue-on-error: true
@@ -183,6 +181,14 @@ jobs:
         uses: ataylorme/eslint-annotate-action@d57a1193d4c59cbfbf3f86c271f42612f9dbd9e9 # 3.0.0
         with:
           report-json: reports/lint-report.json
+
+      - name: Fail if tests failed
+        shell: bash
+        if: |
+          steps.tests.outcome != 'success'
+        run: |
+          echo "Tests failed"
+          exit 1;
 
   npm-test:
     name: Test the code
